server:
  port: 8080
  host: "0.0.0.0"

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "app_db"
  ssl_mode: "disable"

logger:
  level: "info"
  format: "json"

app:
  name: "golang-server-template"
  version: "1.0.0"
  environment: "development"
  debug: true
